### ISSUE TITLE
Use native slider instead of rangeslider

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-slider#161]
### Subject of the issue/enhancement/features
Would be good to try if we can use native input type=range for the Slider. [Browser support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) looks good. 
Biggest issue will be a similar [cross browser design](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/). This [demo](https://codepen.io/chriscoyier/pen/FtnAa) works and looks good in IE, Chrome and Firefox.

### Reasons
It seems that using a 3rd party library has the same time cost as the old self built slider, but with less control over the behaviour. We have now gotten rid of ie8>ie10 so it might be time to move back to using browser native behaviour.

**Comment by chris-steele** [comment]
I'm happy to look at this. @guywillis, @kirsty-hames what are your fed-angled thoughts on this?

**Comment by guywillis** [comment]
I think it would be better from an accessibility perspective to revert to browser default. 

We'll probably be a touch more limited on the visual side of things in the short term but the visual treatments of the browser default elements have improved since we swapped to rangeslider and continue to improve.

**Comment by chris-steele** [comment]
May help with https://github.com/adaptlearning/adapt-contrib-slider/issues/158 also

**Comment by chris-steele** [comment]
5 years on...

**Comment by oliverfoster** [comment]
Love you man.

**Comment by chris-steele** [comment]
back atcha
