### ISSUE TITLE
Allow slide step prefix and suffix

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-slider#173]
### Subject of the enhancement
We would like to be able to add a prefix and suffix to each step of the slider.  Since `_scaleStart`, `_scaleEnd` and `_scaleStep` must be numeric, we can't use values in other formats (ex. currency).

I would propose adding `scaleStepPrefix` and `scaleStepSuffix` as new JSON options.

```
"scaleStepPrefix": "$",
"scaleStepSuffix": "K",
```

Would anyone else find this feature useful?  If so, I will create a PR.

### Screenshots

**Example (dollars in thousands):**
![dollars](https://user-images.githubusercontent.com/898168/215190232-22cd688e-7dda-4705-9e94-1435c494a936.jpg)

**Example (voltage):**
![voltage](https://user-images.githubusercontent.com/898168/215190269-7d441342-8279-4134-bfc1-cf844d5380cc.jpg)

**Example (measurement in inches):**
![inches](https://user-images.githubusercontent.com/898168/215190312-db75d325-5318-493f-9c7f-9ee6df36b52e.jpg)

**Comment by guywillis** [comment]
I think this would be a great addition, @swashbuck

**Comment by swashbuck** [comment]
Will wait on #172 to be approved and merged.
