### ISSUE TITLE
Enhancement: Ability to have a decimal scale

### ISSUE THREAD

**Issue by paulstevendev** [adaptlearning/adapt-contrib-slider#193]
Enhancement request: Ability to have decimals e.g a scale of 1.0 to 2.0

It would be great if this component could support a scale of decimals. You can display a decimal scale but it only allows you to select the whole numbers.

![image](https://github.com/adaptlearning/adapt-contrib-slider/assets/114067294/8008c733-bb98-4482-894c-7494405405d1)

**Comment by oliverfoster** [comment]
Please try the code in the pr attached

**Comment by paulstevendev** [comment]
Wow that us a rapid response - thank you! I will give it a test.

**Comment by paulstevendev** [comment]
Looking and working well

![image](https://github.com/adaptlearning/adapt-contrib-slider/assets/114067294/8f5a54aa-2bf0-4982-ad88-d8fa9afde1c6)
