### ISSUE TITLE
model/user answer doesnt work when using _correctAnswer 

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-contrib-slider#59]
I have a slider in which single value is correct, I've set it with `_correctAnswer` but then model answer/user answer doesnt work (dont indicate the correct answer - always stays on user answer - marker). I have to put it in `_correctRage` leaving `_correctAnswer` empty

This is not working

        "_correctAnswer": 60,

This works

        "_correctAnswer": "",
        "_correctRange": {
            "_bottom": 60,
            "_top": 60
        },

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-476
