### ISSUE TITLE
Invalid comparator used

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-slider#61]
https://github.com/adaptlearning/adapt-contrib-slider/blob/develop/js/adapt-contrib-slider.js#L330-L332

Does not allow for correct range starting at 0 as 0 == "".
Should be using a type-wise comparator such that 0 !== "".

**Comment by zenduo** [comment]
Hey @oliverfoster give me a shout on Skype about this one and I'll take a look if its a quick fix.

**Comment by oliverfoster** [comment]
Hey Alan, this applies to lines 356 and 358 now. If the bottom correct range is 0 then the != "" doesn't work as an 'unspecified' comparison. Needs the double equals.

**Comment by zenduo** [comment]
Hey Ollie, have been taking a look at this one, as soon as i use !== undefined in the top line it then assumes that we are using _correctAnswer for the component, even though this value in the component json is blank or "".

On the plus side the bottom line works well with it. Any ideas on how to solve the top line as this stops the bottom from working?

if(this.model.get('_correctAnswer') !== undefined) {
     answers.push('top'+this.model.get('_correctAnswer'));
} else if(bottom !== undefined) {

**Comment by zenduo** [comment]
Updated in the latest PR https://github.com/zenduo/adapt-contrib-slider/commit/1640a3046abc38082ff45c0dadb8998b6f282bd2
