### ISSUE TITLE
Missing label properties in the builder

### ISSUE THREAD

**Issue by samumist** [adaptlearning/adapt-contrib-slider#63]
![screen shot 2015-04-23 at 22 56 27](https://cloud.githubusercontent.com/assets/3883086/7313104/c62d8bae-ea88-11e4-972a-ef1d469df7a9.png)
no labelStart and labelEnd property field of the slider component in the authoring tool. They didn't make it into the properties.schema.

**Comment by zenduo** [comment]
This has been merged into master, so closing.
