### ISSUE TITLE
_showNumber set to false still shows number

### ISSUE THREAD

**Issue by samumist** [adaptlearning/adapt-contrib-slider#87]
I've set the `_showNumber` to `false` and  ` "_showScaleIndicator": true, "_showScale": true`, the number still show. 

When I set the `_showScale` to false, it does hide the number.

Don't know if this is a bug or not.

Environment:
Mac, Chrome with latest framework.

**Comment by moloko** [comment]
just tried this, seems OK to me? I had the following settings:
```
"_showNumber": false,
"_showScaleIndicator": true,
"_showScale": true
```
And the output looked like this:
![slider_shownumber](https://cloud.githubusercontent.com/assets/1249597/10967169/8545c842-83b0-11e5-927f-247866d04a47.jpg)

**Comment by moloko** [comment]
I can see that if `_showScaleIndicator` is `false` then `_showNumber: true` doesn't work - but that sort-of makes sense since there is nothing to show the number on...

**Comment by samumist** [comment]
Your screenshot also has the "1, 2 (which is blocked by the pointer), 3, 4) shown. I thought when you set `_showNumber` to `false`, you hide these numbers. 

Seems I misunderstood this.

I'm working on a range of 10 to 100 with a step of 10 which seems not yet supported at the moment. Thus following an wordaround by Ollie, I just use 1-10 for the scale but hide the numbers scale then use labelStart and LabelEnd to show the number like in this following screenshot. 

![slider](https://cloud.githubusercontent.com/assets/3883086/10968096/e8e134d8-83f9-11e5-9cf8-7a6235d03b31.jpg)

**Comment by moloko** [comment]
yes, `_showScale` is what toggles the display of the display of the numbers shown along the length of the slider

I'll add a feature request for a 'step range' as this seems like a useful thing to have

**Comment by samumist** [comment]
Many thanks.
