### ISSUE TITLE
Setting _showScaleIndicator to false does not hide the indicators

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-slider#88]
I would expect this to hide the indicators, when this is set to `false`.  It doesn't seem to do that.

**Comment by moloko** [comment]
this works OK for me... this is with it set to `true`:
![slider_showscaleindicator-true](https://cloud.githubusercontent.com/assets/1249597/10999801/f756c73e-8495-11e5-9a0f-8a5486aa4fda.png)
and this is with it set to `false`:
![slider_showscaleindicator-false](https://cloud.githubusercontent.com/assets/1249597/10999809/02597352-8496-11e5-9254-c039281c1f96.png)

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#864
