### ISSUE TITLE
Option to let the slider-bar update on drag with the handle

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt-contrib-slider#89]
Would it be possible to add an an option to enable the slider bar to be updated in 'real time' when the handle is dragged around. Rather then waiting for cursor to be released and then being updated.

![slider](https://cloud.githubusercontent.com/assets/1676635/11300489/6dbcbfe0-8f87-11e5-8a57-b105cc73566d.jpg)

**Comment by moloko** [comment]
Good idea. Moved to https://adaptlearning.atlassian.net/browse/ABU-1131
